spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_EXTERNAL_URL}/realms/${KC_REALM}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  servlet:
    context-path: /api
  port: 8080
logging:
  level:
    org:
      bazar: ${LOGGING_LEVEL}
management:
  server:
    port: 8090
kafka:
  space-delete:
    topic: space-delete
    group-id: space-delete-group
scheduler:
  message:
    deleteMessages: "0 0 3 * * *"