# Создай локально application-local.yaml и скопируй содержимое этого файла туда (если нужно, что-то поменяй).
# Не забудь добавить профиль local в конфигурацию запуска!
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bazar_chat
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/local
  kafka:
    bootstrap-servers: localhost:9092
logging:
  level:
    org:
      bazar: ${LOGGING_LEVEL:DEBUG}